[package]
name = "exploit-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["legacy"]}
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.39"
hex = { version = "0.4.3", default-features = false, features = ["std"] }
futures = "0.3.15"

[build-dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
